GET http://localhost:8080/posts

### Create post

POST http://localhost:8080/posts HTTP/1.1
content-type: application/json

{
    "firstName": "Dianery",
    "lastName": "Marin",
    "email": "dianerymarin@gmail.com",
    "favoriteColor": "pink",
    "birthday": "01/29/2000"
}

### PUT post

PUT http://localhost:8080/posts/63bf636b644c41ff91a7ab78 HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Flores",
    "email": "josueflores@gmail.com",
    "favoriteColor": "blue",
    "birthday": "07/06/2002"
}

### DELETE post

DELETE http://localhost:8080/posts/63bf636b644c41ff91a7ab78 HTTP/1.1

### Create post

POST https://personal-project.onrender.com/posts HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Marin",
    "email": "josuemarin@gmail.com",
    "favoriteColor": "blue",
    "birthday": "07/06/2002"
}

### PUT post

PUT https://personal-project.onrender.com/posts/63ccdb7abdaa6e5f8ec1b020 HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Flores",
    "email": "josueflores@gmail.com",
    "favoriteColor": "blue",
    "birthday": "07/06/2002"
}

### DELETE post

DELETE https://personal-project.onrender.com/posts/63ccdb7abdaa6e5f8ec1b020 HTTP/1.1