GET http://localhost:8080/posts

### Create post

POST http://localhost:8080/posts HTTP/1.1
content-type: application/json

{
    "firstName": "Dianery",
    "lastName": "Marin",
    "post": "Eiusbafewb."
}

### PUT post

PUT http://localhost:8080/posts/63bf636b644c41ff91a7ab78 HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Flores",
    "post": "Eiusbafewb iluhfl we ef ije flj bldjh bvljhvb ldvb ldkjvbl dsijvbds livjbd slvij lidjbv iu hfilf wklfcb llkcfb sdjcb jh vjdhvb jh liuhf el eweh weuh."
}

### DELETE post

DELETE http://localhost:8080/posts/63bf636b644c41ff91a7ab78 HTTP/1.1

### Create post

POST https://personal-project.onrender.com/posts HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Marin",
    "post": "Eiusbafewb iluhfl we ef ije flj bldjh bvljhvb ldvb ldkjvbl dsijvbds livjbd slvij lidjbv iu hfilf wklfcb llkcfb sdjcb jh vjdhvb jh liuhf el eweh weuh."
}

### PUT post

PUT https://personal-project.onrender.com/posts/63ccdb7abdaa6e5f8ec1b020 HTTP/1.1
content-type: application/json

{
    "firstName": "Josue",
    "lastName": "Flores",
    "post": "Eiusbafewb iluhfl we ef ije flj bldjh bvljhvb ldvb ldkjvbl dsijvbds livjbd slvij lidjbv iu hfilf wklfcb llkcfb sdjcb jh vjdhvb jh liuhf el eweh weuh."
}

### DELETE post

DELETE https://personal-project.onrender.com/posts/63ccdb7abdaa6e5f8ec1b020 HTTP/1.1